### ISSUE TITLE
Kernel dead with TypeError:environment can only contain strings error

### ISSUE THREAD

**Issue by vdakshin** [Bachmann1234/java9_kernel#15]
Hi Got everything installed and configured. But I am on anaconda python 2.7.11. Kernel dead everytime I launch it with the following traceback:

Traceback (most recent call last):
  File "C:\Anaconda2\lib\site-packages\notebook\base\handlers.py", line 458, in wrapper
    result = yield gen.maybe_future(method(self, _args, *_kwargs))
  File "C:\Anaconda2\lib\site-packages\tornado\gen.py", line 1008, in run
    value = future.result()
  File "C:\Anaconda2\lib\site-packages\tornado\concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "C:\Anaconda2\lib\site-packages\tornado\gen.py", line 1014, in run
    yielded = self.gen.throw(_exc_info)
  File "C:\Anaconda2\lib\site-packages\notebook\services\sessions\handlers.py", line 58, in post
    sm.create_session(path=path, kernel_name=kernel_name))
  File "C:\Anaconda2\lib\site-packages\tornado\gen.py", line 1008, in run
    value = future.result()
  File "C:\Anaconda2\lib\site-packages\tornado\concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "C:\Anaconda2\lib\site-packages\tornado\gen.py", line 1014, in run
    yielded = self.gen.throw(_exc_info)
  File "C:\Anaconda2\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 73, in create_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Anaconda2\lib\site-packages\tornado\gen.py", line 1008, in run
    value = future.result()
  File "C:\Anaconda2\lib\site-packages\tornado\concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "C:\Anaconda2\lib\site-packages\tornado\gen.py", line 282, in wrapper
    yielded = next(result)
  File "C:\Anaconda2\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 87, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Anaconda2\lib\site-packages\jupyter_client\multikernelmanager.py", line 109, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Anaconda2\lib\site-packages\jupyter_client\manager.py", line 244, in start_kernel
    *_kw)
  File "C:\Anaconda2\lib\site-packages\jupyter_client\manager.py", line 190, in _launch_kernel
    return launch_kernel(kernel_cmd, *_kw)
  File "C:\Anaconda2\lib\site-packages\jupyter_client\launcher.py", line 108, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Anaconda2\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Anaconda2\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
TypeError: environment can only contain strings

Looking at the trace seems like it is failing at the Popen because of the unicode object.

Any help is appreciated. Thanks.

**Comment by dsblank** [comment]
Can you post what java expression causes this? 

BTW, I would avoid Python2 if you can.

**Comment by vdakshin** [comment]
It is not any java expression or my code. As soon as I create a new notebook in Jupyter the kernel dies and throws this exception.

**Comment by vdakshin** [comment]
I guess if I can get the kernel to work only with Python3 then I would need to switch.

**Comment by Bachmann1234** [comment]
@vdakshin what are your values for KULLA_HOME and JAVA_9_HOME?

**Comment by vdakshin** [comment]
JAVA_9_HOME C:\Program Files\Java\jdk-9
KULLA_HOME C:\Kulla\kulla.jar

**Comment by Bachmann1234** [comment]
@vdakshin I did some research. Sadly I don't have a real answer for you. I found some other people getting similar error messages (https://github.com/conda/conda-build/commit/e118501f418ff76873a49e3dc19b0ce4a13ea3e9) but we don't do anything involving coercing environment variables to unicode as far as I can tell. I thought maybe your paths had some sort of unicode in it but they look fine to me. 

Python 3 would likely work but I get that is a frustrating answer...

One other thing you can try. So if you are loading those two values via the json file. Try deleting those lines and just defining them in your windows environment (http://www.computerhope.com/issues/ch000549.htm) 

If you have them defined in the environment already, try deleting those keys and defining them in the JSON.

Other than that I just dont know whats going on.

**Comment by vdakshin** [comment]
@Bachmann1234 Thanks for the suggestions. I tried both deleting the environment paths in the JSON file as well as in Windows environment. When I left it in the JSON file, i got the same unicode error as above.

When I left it in the Windows System variables and removed it from the JSON file, I got the following traceback which is different with an import error about pexpect :

Traceback (most recent call last):
  File "C:\Anaconda2\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\java9_kernel-master\java9_kernel-master\javakernel__main__.py", line 1, in <module>
    from kernel import JavaKernel
  File "C:\java9_kernel-master\java9_kernel-master\javakernel\kernel.py", line 14, in <module>
    from pexpect import replwrap, EOF
ImportError: No module named pexpect
[I 09:42:39.760 NotebookApp] KernelRestarter: restarting kernel (1/5)
Traceback (most recent call last):
  File "C:\Anaconda2\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\java9_kernel-master\java9_kernel-master\javakernel__main__.py", line 1, in <module>
    from kernel import JavaKernel
  File "C:\java9_kernel-master\java9_kernel-master\javakernel\kernel.py", line 14, in <module>
    from pexpect import replwrap, EOF
ImportError: No module named pexpect
[I 09:42:42.772 NotebookApp] KernelRestarter: restarting kernel (2/5)
Traceback (most recent call last):
  File "C:\Anaconda2\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\java9_kernel-master\java9_kernel-master\javakernel__main__.py", line 1, in <module>
    from kernel import JavaKernel
  File "C:\java9_kernel-master\java9_kernel-master\javakernel\kernel.py", line 14, in <module>
    from pexpect import replwrap, EOF
ImportError: No module named pexpect
[I 09:42:45.798 NotebookApp] KernelRestarter: restarting kernel (3/5)
Traceback (most recent call last):
  File "C:\Anaconda2\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\java9_kernel-master\java9_kernel-master\javakernel__main__.py", line 1, in <module>
    from kernel import JavaKernel
  File "C:\java9_kernel-master\java9_kernel-master\javakernel\kernel.py", line 14, in <module>
    from pexpect import replwrap, EOF
ImportError: No module named pexpect
[W 09:42:46.770 NotebookApp] Timeout waiting for kernel_info reply from 2c5e6b70-0357-4ef6-91de-f75e6bcc71c0
[I 09:42:48.811 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel 2c5e6b70-0357-4ef6-91de-f75e6bcc71c0 restarted
Traceback (most recent call last):
  File "C:\Anaconda2\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\java9_kernel-master\java9_kernel-master\javakernel__main__.py", line 1, in <module>
    from kernel import JavaKernel
  File "C:\java9_kernel-master\java9_kernel-master\javakernel\kernel.py", line 14, in <module>
    from pexpect import replwrap, EOF
ImportError: No module named pexpect
[W 09:42:51.826 NotebookApp] KernelRestarter: restart failed
[W 09:42:51.828 NotebookApp] Kernel 2c5e6b70-0357-4ef6-91de-f75e6bcc71c0 died, removing from map.
ERROR:root:kernel 2c5e6b70-0357-4ef6-91de-f75e6bcc71c0 restarted failed!
[W 09:42:51.881 NotebookApp] Kernel deleted before session
[W 09:42:51.881 NotebookApp] 410 DELETE /api/sessions/1f6b62a7-23b6-4125-9601-30501e6f1b9b (::1) 2.00ms referer=http://localhost:8888/notebooks/Untitled2.ipynb?kernel_name=java

Any ideas based on this? Thanks very much!

**Comment by Bachmann1234** [comment]
ImportError: No module named pexpect

Try `pip install pexpect`

**Comment by vdakshin** [comment]
I now get the error: AttributeError: 'module' object has no attribute 'spawn'

It seems to fail at the continuation_prompt:

  File "C:\java9_kernel-master\java9_kernel-master\javakernel\kernel.py", line 52, in _start_java_repl
    continuation_prompt=u'>>'

I checked to make sure that pexpect is imported. This is the file that the import points to:

C:\Anaconda2\lib\site-packages\pexpect__init__.pyc

Thanks.

**Comment by Bachmann1234** [comment]
Well that one has me stumped. My only guess is to try and clear all the .pyc files and see if something was just stale

**Comment by vdakshin** [comment]
Let me know if this is not going to go anywhere.

But with clearing the .pyc files I get a new error:

  File "C:\Anaconda2\lib\site-packages\pexpect\replwrap.py", line 38, in **init**
    self.child = pexpect.spawn(cmd_or_spawn, echo=False, encoding='utf-8')
TypeError: **init**() got an unexpected keyword argument 'encoding'

**Comment by vdakshin** [comment]
I finally got the Kernel to run with a little bit of tweaking the replwrap.py.

So now I get the following statements in the console:

java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+103-2016-01-27-183833.javare.4341.nc)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+103-2016-01-27-183833.javare.4341.nc, mixed mode)

But it does not seem to execute the code. for example:

System.out.println("Test");

does nothing. Any ideas? Thanks much!

**Comment by dsblank** [comment]
It sounds like you have the wrong version of pexpect. It should not need any tweaking. It is hard to say what the issue is, given that you have changed some code.

There may be some issues that Python3 fixes. I can only confirm that I am running with Python3 on Linux with many students and it is working well:

https://athena.brynmawr.edu/jupyter/hub/dblank/public/CS206%20Data%20Structures/2016-Spring/Notebooks

**Comment by Bachmann1234** [comment]
@vdakshin try something like `3 + 4` printlines are a weird example for a REPL since they dont really have a return value rather they are just side effects.

**Comment by vdakshin** [comment]
Actually my fix was what was causing the problem so it did not work.

I then went ahead and installed python 3.5 and tried running it under that.

I still get the attribute error for pexpect. Here is a snapshot of the trace:

C:\Anaconda2\envs\py35\lib\site-packages\pexpect\replwrap.py in **init**(self=<pexpect.replwrap.REPLWrapper object>, cmd_or_spawn=r'C:\Progra~1\Java\jdk-9/bin/java -jar C:\Kulla\kulla.jar', orig_prompt='->', prompt_change=None, new_prompt='[PEXPECT_PROMPT>', continuation_prompt='>>', extra_init_cmd=None)
     36                  extra_init_cmd=None):
     37         if isinstance(cmd_or_spawn, basestring):
---> 38             self.child = pexpect.spawn(cmd_or_spawn, echo=False, encoding='utf-8')
        self.child = undefined
        global pexpect.spawn = undefined
        cmd_or_spawn = 'C:\Progra~1\Java\jdk-9/bin/java -jar C:\Kulla\kulla.jar'
        global echo = undefined
        global encoding = undefined
     39         else:
     40             self.child = cmd_or_spawn

AttributeError: module 'pexpect' has no attribute 'spawn'

**Comment by Bachmann1234** [comment]
Honestly, no idea. your best bet at this point is trying a fresh environment. Like creating a http://docs.python-guide.org/en/latest/dev/virtualenvs/ and trying to get this working there.
