### ISSUE TITLE
Is this work on windows10

### ISSUE THREAD

**Issue by dchen23** [Bachmann1234/java9_kernel#23]
I follow the instruction and get this : 
`C:\Users\chick>jupyter console --kernel java
[ZMQTerminalIPythonApp] ERROR | Failed to run command:
['python3', 'C:\Users\chick\.ipython\kernels\java9_kernel-master\javakernel', '-f', 'C:\Users\chick\AppData\Roaming\jupyter\runtime\kernel-10532.json']
    PATH='C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\Calibre2\;C:\Program Files (x86)\Brackets\command;C:\Go\bin;C:\Program Files\nodejs\;C:\Program Files\Java\jdk1.8.0_102\bin;C:\Program Files (x86)\scala\bin;C:\Program Files (x86)\sbt\\bin;C:\Ruby23-x64\bin;C:\Users\chick\AppData\Local\Programs\Python\Python35-32\Scripts\;C:\Users\chick\AppData\Local\Programs\Python\Python35-32\;C:\Users\chick\AppData\Local\atom\bin;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\chick\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\GnuWin32\bin;C:\Users\chick\AppData\Roaming\npm'
    with kwargs:
{'cwd': None, 'stdout': None, 'stdin': -1, 'stderr': None}

Traceback (most recent call last):
  File "c:\users\chick\appdata\local\programs\python\python35-32\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\chick\appdata\local\programs\python\python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\chick\AppData\Local\Programs\Python\Python35-32\Scripts\jupyter-console.EXE__main__.py", line 9, in <module>
  File "c:\users\chick\appdata\local\programs\python\python35-32\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "c:\users\chick\appdata\local\programs\python\python35-32\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-114>", line 2, in initialize
  File "c:\users\chick\appdata\local\programs\python\python35-32\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, _args, *_kwargs)
  File "c:\users\chick\appdata\local\programs\python\python35-32\lib\site-packages\jupyter_console\app.py", line 137, in initialize
    self.init_shell()
  File "c:\users\chick\appdata\local\programs\python\python35-32\lib\site-packages\jupyter_console\app.py", line 105, in init_shell
    JupyterConsoleApp.initialize(self)
  File "c:\users\chick\appdata\local\programs\python\python35-32\lib\site-packages\jupyter_client\consoleapp.py", line 334, in initialize
    self.init_kernel_manager()
  File "c:\users\chick\appdata\local\programs\python\python35-32\lib\site-packages\jupyter_client\consoleapp.py", line 288, in init_kernel_manager
    self.kernel_manager.start_kernel(**kwargs)
  File "c:\users\chick\appdata\local\programs\python\python35-32\lib\site-packages\jupyter_client\manager.py", line 243, in start_kernel
    *_kw)
  File "c:\users\chick\appdata\local\programs\python\python35-32\lib\site-packages\jupyter_client\manager.py", line 189, in _launch_kernel
    return launch_kernel(kernel_cmd, *_kw)
  File "c:\users\chick\appdata\local\programs\python\python35-32\lib\site-packages\jupyter_client\launcher.py", line 123, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "c:\users\chick\appdata\local\programs\python\python35-32\lib\subprocess.py", line 950, in **init**
    restore_signals, start_new_session)
  File "c:\users\chick\appdata\local\programs\python\python35-32\lib\subprocess.py", line 1220, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified`

**Comment by Bachmann1234** [comment]
Honestly not sure. The kernel itself seems to have stopped working with the latest ipython. I have not made the time to try and get it working yet.

**Comment by dchen23** [comment]
Thx for reply, this project is awesome, I will follow
